name: deploy-ta-jobs-category

on: 
  push:
    branches:
      - master
    paths:
      - 'ta-jobs-category/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ta-jobs-category && docker build -t rommycy00/ta-jobs-category .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rommycy00/ta-jobs-category
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ta-vrilance
      - run: kubectl rollout restart deployment ta-jobs-category-depl